version: "3.8"

services:
  app:
    build: .
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: postgres:12.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: localtest