server:
  port: 8090
  tomcat.max-threads: 100

spring:
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB
  datasource:
    driver: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connectionTimeout: 15000
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false